[http]
bind = ":8081"
assetsdir = "assets"
secretkey = "47cd4a7b1f1e40a397b398"
uploaddir = "e:/photos"

[grpc]
addr = "127.0.0.1:50051"
cert = "../certs/cert.pem"
host = "aitour.com"

[db]
host = "joytour.top"
port = 5432
user = "aitour"
password = "aitour"
dbname = "aitour"

[options]
weatherapikey="f582f8a21b3b8b3f0f20a8a01789f217"
googlemapapikey="AIzaSyCWtUXDMua8oelbSQzgFW7rHtg7rXO-eZg"
googlemapdomain="ditu.google.cn"


